// ── 366 Daily Quotes for Mindful Eating ──────────────────────────────────────
// Real quotes from notable figures specifically about food, eating, body respect,
// nutrition, fasting, and mindful consumption.

export interface DailyQuote {
  text: string;
  author: string;
}

export const DAILY_QUOTES: DailyQuote[] = [
  // January (1-31) — Food as Medicine
  { text: "Let food be thy medicine and medicine be thy food.", author: "Hippocrates" },
  { text: "One cannot think well, love well, sleep well, if one has not dined well.", author: "Virginia Woolf" },
  { text: "When diet is wrong, medicine is of no use. When diet is correct, medicine is of no need.", author: "Ayurvedic Proverb" },
  { text: "The food you eat can be either the safest and most powerful form of medicine or the slowest form of poison.", author: "Ann Wigmore" },
  { text: "Every time you eat or drink, you are either feeding disease or fighting it.", author: "Heather Morgan" },
  { text: "Leave your drugs in the chemist's pot if you can heal the patient with food.", author: "Hippocrates" },
  { text: "No disease that can be treated by diet should be treated with any other means.", author: "Maimonides" },
  { text: "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition.", author: "Thomas Edison" },
  { text: "All disease begins in the gut.", author: "Hippocrates" },
  { text: "Our food should be our medicine and our medicine should be our food.", author: "Hippocrates" },
  { text: "If we could give every individual the right amount of nourishment and exercise, we would have found the safest way to health.", author: "Hippocrates" },
  { text: "A wise man ought to realize that health is his most valuable possession.", author: "Hippocrates" },
  { text: "Those who think they have no time for healthy eating will sooner or later have to find time for illness.", author: "Edward Stanley" },
  { text: "The wise man should consider that health is the greatest of human blessings.", author: "Hippocrates" },
  { text: "Natural forces within us are the true healers of disease.", author: "Hippocrates" },
  { text: "Everyone has a doctor in him or her; we just have to help it in its work. The natural healing force within each of us is the greatest force in getting well. Our food should be our medicine.", author: "Hippocrates" },
  { text: "Healing is a matter of time, but it is sometimes also a matter of opportunity.", author: "Hippocrates" },
  { text: "Make food your medicine before you have to make medicine your food.", author: "Terri Guillemets" },
  { text: "The function of protecting and developing health must rank even above that of restoring it when it is impaired.", author: "Hippocrates" },
  { text: "Before you heal someone, ask him if he's willing to give up the things that made him sick.", author: "Hippocrates" },
  { text: "Prevention is better than cure.", author: "Desiderius Erasmus" },
  { text: "An ounce of prevention is worth a pound of cure.", author: "Benjamin Franklin" },
  { text: "Nature heals, the doctor only helps.", author: "Paracelsus" },
  { text: "The art of healing comes from nature, not from the physician.", author: "Paracelsus" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "Your body is a temple, but only if you treat it as one.", author: "Astrid Alauda" },
  { text: "The body is your temple. Keep it pure and clean for the soul to reside in.", author: "B.K.S. Iyengar" },
  { text: "Your body is precious. It is our vehicle for awakening. Treat it with care.", author: "Buddha" },
  { text: "To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.", author: "Buddha" },
  { text: "Health is the greatest gift, contentment the greatest wealth.", author: "Buddha" },
  { text: "Keeping your body healthy is an expression of gratitude to the whole cosmos.", author: "Thich Nhat Hanh" },

  // February (32-60) — Eating with Awareness
  { text: "When walking, walk. When eating, eat.", author: "Zen Proverb" },
  { text: "When you eat, just eat. When you walk, just walk.", author: "Thich Nhat Hanh" },
  { text: "Drink your tea slowly and reverently, as if it is the axis on which the world earth revolves.", author: "Thich Nhat Hanh" },
  { text: "Mindful eating is a way to become reacquainted with the guidance of our internal nutritionist.", author: "Jan Chozen Bays" },
  { text: "Mindful eating means simply eating or drinking while being aware of each bite or sip.", author: "Thich Nhat Hanh" },
  { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh" },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh" },
  { text: "Tell me what you eat, and I will tell you who you are.", author: "Jean Anthelme Brillat-Savarin" },
  { text: "The discovery of a new dish does more for the happiness of the human race than the discovery of a star.", author: "Jean Anthelme Brillat-Savarin" },
  { text: "Animals feed; man eats; only the man of intellect knows how to eat.", author: "Jean Anthelme Brillat-Savarin" },
  { text: "The destiny of nations depends on how they nourish themselves.", author: "Jean Anthelme Brillat-Savarin" },
  { text: "To eat is a necessity, but to eat intelligently is an art.", author: "François de La Rochefoucauld" },
  { text: "There is no love sincerer than the love of food.", author: "George Bernard Shaw" },
  { text: "Part of the secret of success in life is to eat what you like and let the food fight it out inside.", author: "Mark Twain" },
  { text: "Life is too short for fake butter, cheese, or people.", author: "Unknown" },
  { text: "Cooking is like love. It should be entered into with abandon or not at all.", author: "Harriet Van Horne" },
  { text: "People who love to eat are always the best people.", author: "Julia Child" },
  { text: "The only time to eat diet food is while you're waiting for the steak to cook.", author: "Julia Child" },
  { text: "Life is uncertain. Eat dessert first.", author: "Ernestine Ulmer" },
  { text: "First we eat, then we do everything else.", author: "M.F.K. Fisher" },
  { text: "One of the very nicest things about life is the way we must regularly stop whatever it is we are doing and devote our attention to eating.", author: "Luciano Pavarotti" },
  { text: "Food is our common ground, a universal experience.", author: "James Beard" },
  { text: "Food is symbolic of love when words are inadequate.", author: "Alan D. Wolfelt" },
  { text: "Food is not just eating energy. It's an experience.", author: "Guy Fieri" },
  { text: "Food, like a loving touch or a glimpse of divine power, has that ability to comfort.", author: "Norman Kolpas" },
  { text: "There is no sight on earth more appealing than the sight of a woman making dinner for someone she loves.", author: "Thomas Wolfe" },
  { text: "Cooking is at once child's play and adult joy. And cooking done with care is an act of love.", author: "Craig Claiborne" },
  { text: "Good food is the foundation of genuine happiness.", author: "Auguste Escoffier" },
  { text: "A recipe has no soul. You, as the cook, must bring soul to the recipe.", author: "Thomas Keller" },

  // March (61-90) — Moderation and Self-Control
  { text: "One should eat to live, not live to eat.", author: "Molière" },
  { text: "Thou shouldst eat to live; not live to eat.", author: "Socrates" },
  { text: "Eat breakfast like a king, lunch like a prince, and dinner like a pauper.", author: "Adelle Davis" },
  { text: "We never repent of having eaten too little.", author: "Thomas Jefferson" },
  { text: "Hara hachi bu — eat until you are 80% full.", author: "Okinawan Proverb" },
  { text: "The more you eat, the less flavor; the less you eat, the more flavor.", author: "Chinese Proverb" },
  { text: "Eat little, sleep sound.", author: "Iranian Proverb" },
  { text: "Gluttony is an emotional escape, a sign something is eating us.", author: "Peter De Vries" },
  { text: "Hunger is the best sauce in the world.", author: "Miguel de Cervantes" },
  { text: "It is better to rise from life as from a banquet – neither thirsty nor drunken.", author: "Aristotle" },
  { text: "Moderation in all things, especially moderation.", author: "Ralph Waldo Emerson" },
  { text: "Moderation. Small helpings. Sample a little bit of everything. These are the secrets of happiness and good health.", author: "Julia Child" },
  { text: "The belly rules the mind.", author: "Spanish Proverb" },
  { text: "Better to pay the butcher than the doctor.", author: "Yiddish Proverb" },
  { text: "After dinner rest a while; after supper walk a mile.", author: "T. Cogan" },
  { text: "He that eats till he is sick must fast till he is well.", author: "English Proverb" },
  { text: "A full belly is the mother of all evil.", author: "Benjamin Franklin" },
  { text: "Eat not to dullness; drink not to elevation.", author: "Benjamin Franklin" },
  { text: "To lengthen thy life, lessen thy meals.", author: "Benjamin Franklin" },
  { text: "I saw few die of hunger; of eating, a hundred thousand.", author: "Benjamin Franklin" },
  { text: "Eat few suppers, and you'll need few medicines.", author: "Benjamin Franklin" },
  { text: "By suppers more have been killed than Galen ever cured.", author: "George Herbert" },
  { text: "A man too busy to take care of his health is like a mechanic too busy to take care of his tools.", author: "Spanish Proverb" },
  { text: "He who eats alone chokes alone.", author: "Arabian Proverb" },
  { text: "The fool that eats till he is sick must fast till he is well.", author: "George Thornbury" },
  { text: "Many dishes, many diseases.", author: "English Proverb" },
  { text: "To safeguard one's health at the cost of too strict a diet is a tiresome illness indeed.", author: "François de La Rochefoucauld" },
  { text: "All things are poison, and nothing is without poison; only the dose permits something not to be poisonous.", author: "Paracelsus" },
  { text: "The secret of staying young is to live honestly, eat slowly, and lie about your age.", author: "Lucille Ball" },
  { text: "The spirit cannot endure the body when overfed, but, if underfed, the body cannot endure the spirit.", author: "St. Frances de Sales" },

  // April (91-120) — Fasting and Restraint
  { text: "Fasting is the first principle of medicine; fast and see the strength of the spirit reveal itself.", author: "Rumi" },
  { text: "The best of all medicines is resting and fasting.", author: "Benjamin Franklin" },
  { text: "Instead of using medicine, rather, fast a day.", author: "Plutarch" },
  { text: "I fast for greater physical and mental efficiency.", author: "Plato" },
  { text: "Fasting is the greatest remedy – the physician within.", author: "Paracelsus" },
  { text: "A little starvation can really do more for the average sick man than can the best medicines and the best doctors.", author: "Mark Twain" },
  { text: "The light of the world will illuminate within you when you fast and purify yourself.", author: "Mahatma Gandhi" },
  { text: "A genuine fast cleanses the body, mind and soul.", author: "Mahatma Gandhi" },
  { text: "Fasting is a fiery weapon. It has its own science. No one, as far as I am aware, has a perfect knowledge of it.", author: "Mahatma Gandhi" },
  { text: "What the eyes are for the outer world, fasts are for the inner.", author: "Mahatma Gandhi" },
  { text: "Fasting and natural diet, though essentially unknown as a therapy, should be the first treatment when someone discovers that they have a chronic disease.", author: "Joel Fuhrman" },
  { text: "The discipline of fasting breaks the power of food over you.", author: "Jentezen Franklin" },
  { text: "Through the fasting body, the mysteries of the soul are revealed.", author: "St. Ambrose" },
  { text: "Fasting cleanses the soul, raises the mind, subjects one's flesh to the spirit.", author: "St. Augustine" },
  { text: "More than any other practice, fasting reveals the things that control us.", author: "Richard Foster" },
  { text: "When the stomach is full, it is easy to talk of fasting.", author: "St. Jerome" },
  { text: "Fasting is the soul of prayer, mercy is the lifeblood of fasting.", author: "St. Peter Chrysologus" },
  { text: "He who cannot obey himself will be commanded. That is the nature of living creatures.", author: "Friedrich Nietzsche" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Rule your mind or it will rule you.", author: "Horace" },
  { text: "The first and greatest victory is to conquer yourself.", author: "Plato" },
  { text: "Most powerful is he who has himself in his own power.", author: "Seneca" },
  { text: "Self-control is strength. Right thought is mastery. Calmness is power.", author: "James Allen" },
  { text: "The ability to discipline yourself to delay gratification in the short term in order to enjoy greater rewards in the long term is the indispensable prerequisite for success.", author: "Brian Tracy" },
  { text: "He who controls others may be powerful, but he who has mastered himself is mightier still.", author: "Lao Tzu" },
  { text: "Mastering others is strength; mastering yourself is true power.", author: "Lao Tzu" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
  { text: "Self-discipline begins with the mastery of your thoughts. If you don't control what you think, you can't control what you do.", author: "Napoleon Hill" },
  { text: "The real difficulty is to overcome how you think about yourself.", author: "Maya Angelou" },
  { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },

  // May (121-151) — Real Food Philosophy
  { text: "Eat food. Not too much. Mostly plants.", author: "Michael Pollan" },
  { text: "Don't eat anything your great-grandmother wouldn't recognize as food.", author: "Michael Pollan" },
  { text: "If it came from a plant, eat it. If it was made in a plant, don't.", author: "Michael Pollan" },
  { text: "The shared meal elevates eating from a mechanical process of fueling the body to a ritual of family and community.", author: "Michael Pollan" },
  { text: "Don't eat anything incapable of rotting.", author: "Michael Pollan" },
  { text: "Eating is an agricultural act.", author: "Wendell Berry" },
  { text: "People are fed by the food industry, which pays no attention to health, and are treated by the health industry, which pays no attention to food.", author: "Wendell Berry" },
  { text: "The body is not a machine. It is a dynamic, living organism that responds to the quality of what we put into it.", author: "Ann Wigmore" },
  { text: "We are indeed much more than what we eat, but what we eat can nevertheless help us to be much more than what we are.", author: "Adelle Davis" },
  { text: "You are what you eat, so don't be fast, cheap, easy, or fake.", author: "Unknown" },
  { text: "What you eat literally becomes you. You have a choice in what you're made of.", author: "Unknown" },
  { text: "Your diet is a bank account. Good food choices are good investments.", author: "Bethenny Frankel" },
  { text: "Eating crappy food isn't a reward – it's a punishment.", author: "Drew Carey" },
  { text: "You can't out-exercise a bad diet.", author: "Mark Hyman" },
  { text: "Processed foods not only extend the shelf life, but they extend the waistline as well.", author: "Karen Sessions" },
  { text: "Life expectancy would grow by leaps and bounds if green vegetables smelled as good as bacon.", author: "Doug Larson" },
  { text: "The food industry profits from our bad eating habits, but we pay the price with our health.", author: "Joel Fuhrman" },
  { text: "Health is a relationship between you and your body.", author: "Terri Guillemets" },
  { text: "Take care of your body with steadfast fidelity.", author: "Johann Wolfgang von Goethe" },
  { text: "Our bodies are our gardens – our wills are our gardeners.", author: "William Shakespeare" },
  { text: "The human body is the best picture of the human soul.", author: "Ludwig Wittgenstein" },
  { text: "A healthy outside starts from the inside.", author: "Robert Urich" },
  { text: "Health is not valued till sickness comes.", author: "Thomas Fuller" },
  { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
  { text: "It is health that is real wealth and not pieces of gold and silver.", author: "Mahatma Gandhi" },
  { text: "The groundwork for all happiness is good health.", author: "Leigh Hunt" },
  { text: "The greatest wealth is health.", author: "Virgil" },
  { text: "Health is a state of complete harmony of the body, mind, and spirit.", author: "B.K.S. Iyengar" },
  { text: "Time and health are two precious assets that we don't recognize and appreciate until they have been depleted.", author: "Denis Waitley" },
  { text: "He who has health, has hope; and he who has hope, has everything.", author: "Thomas Carlyle" },
  { text: "Healthy citizens are the greatest asset any country can have.", author: "Winston Churchill" },

  // June (152-181) — Emotional Eating and Self-Awareness
  { text: "Compulsive eating is only the symptom; believing that you are not worth your own love is the problem.", author: "Geneen Roth" },
  { text: "It's not about what you're eating, it's about what's eating you.", author: "Geneen Roth" },
  { text: "Awareness is the greatest agent for change.", author: "Eckhart Tolle" },
  { text: "The moment you accept what troubles you've been given, the door will open.", author: "Rumi" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung" },
  { text: "What we do not make conscious emerges later as fate.", author: "Carl Jung" },
  { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Know thyself.", author: "Socrates" },
  { text: "To find yourself, think for yourself.", author: "Socrates" },
  { text: "Self-care is not self-indulgence, it is self-preservation.", author: "Audre Lorde" },
  { text: "Caring for your body, mind, and spirit is your greatest and grandest responsibility.", author: "Deepak Chopra" },
  { text: "I finally realized that being grateful to my body was key to giving more love to myself.", author: "Oprah Winfrey" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
  { text: "What drains your spirit drains your body. What fuels your spirit fuels your body.", author: "Caroline Myss" },
  { text: "The soul always knows what to do to heal itself. The challenge is to silence the mind.", author: "Caroline Myss" },
  { text: "Healing takes courage, and we all have courage, even if we have to dig a little to find it.", author: "Tori Amos" },
  { text: "Nurturing yourself is not selfish – it's essential to your survival and your well-being.", author: "Renee Peterson Trudeau" },
  { text: "Love yourself first and everything else falls into line.", author: "Lucille Ball" },
  { text: "To love oneself is the beginning of a lifelong romance.", author: "Oscar Wilde" },
  { text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha" },
  { text: "Your body hears everything your mind says.", author: "Naomi Judd" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha" },
  { text: "Be patient with yourself. Self-growth is tender; it's holy ground.", author: "Stephen Covey" },
  { text: "The body achieves what the mind believes.", author: "Napoleon Hill" },
  { text: "If you don't take care of your body, where are you going to live?", author: "Unknown" },
  { text: "I believe that the greatest gift you can give your family and the world is a healthy you.", author: "Joyce Meyer" },
  { text: "The wish for healing has always been half of health.", author: "Seneca" },

  // July (182-212) — Simple and Natural Eating
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "The ability to simplify means to eliminate the unnecessary so that the necessary may speak.", author: "Hans Hofmann" },
  { text: "Our life is frittered away by detail. Simplify, simplify.", author: "Henry David Thoreau" },
  { text: "It is not the daily increase but daily decrease. Hack away at the unessential.", author: "Bruce Lee" },
  { text: "To attain knowledge, add things every day. To attain wisdom, remove things every day.", author: "Lao Tzu" },
  { text: "He who knows that enough is enough will always have enough.", author: "Lao Tzu" },
  { text: "Fill your bowl to the brim and it will spill. Keep sharpening your knife and it will blunt.", author: "Lao Tzu" },
  { text: "Be content with what you have; rejoice in the way things are. When you realize nothing is lacking, the whole world belongs to you.", author: "Lao Tzu" },
  { text: "Simplicity, patience, compassion. These three are your greatest treasures.", author: "Lao Tzu" },
  { text: "In dwelling, live close to the ground. In thinking, keep to the simple.", author: "Lao Tzu" },
  { text: "In every walk with nature one receives far more than he seeks.", author: "John Muir" },
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { text: "Study nature, love nature, stay close to nature. It will never fail you.", author: "Frank Lloyd Wright" },
  { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson" },
  { text: "Walking is man's best medicine.", author: "Hippocrates" },
  { text: "The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not.", author: "Mark Twain" },
  { text: "Let nothing which can be treated by diet be treated by other means.", author: "Maimonides" },
  { text: "Attention to the health of the body is one of the most important duties of the statesman.", author: "Maimonides" },
  { text: "A cheerful heart is good medicine, but a crushed spirit dries up the bones.", author: "King Solomon" },
  { text: "The greatest medicine of all is teaching people how not to need it.", author: "Hippocrates" },
  { text: "Healing begins with an aromatic kitchen.", author: "Esau Phiri" },
  { text: "He that takes medicine and neglects diet, wastes the skill of the physician.", author: "Chinese Proverb" },
  { text: "Your body is not a temple, it's an amusement park. Enjoy the ride.", author: "Anthony Bourdain" },
  { text: "Food is everything we are. It's an extension of nationalist feeling, ethnic feeling, your personal history, your province, your region, your tribe, your grandma.", author: "Anthony Bourdain" },
  { text: "I think food, culture, people and landscape are all absolutely inseparable.", author: "Anthony Bourdain" },
  { text: "Context and memory play powerful roles in all the truly great meals in one's life.", author: "Anthony Bourdain" },
  { text: "Good food is very often, even most often, simple food.", author: "Anthony Bourdain" },
  { text: "Skills can be taught. Character you either have or you don't have.", author: "Anthony Bourdain" },
  { text: "If I'm an advocate for anything, it's to move. As far as you can, as much as you can.", author: "Anthony Bourdain" },
  { text: "Do we really want to travel in hermetically sealed popemobiles through the rural provinces of France, Mexico and the Far East, eating only in Hard Rock Cafes and McDonald's?", author: "Anthony Bourdain" },

  // August (213-243) — The Joy and Culture of Eating
  { text: "Food brings people together on many different levels. It's nourishment of the soul and body; it's truly love.", author: "Giada De Laurentiis" },
  { text: "A good cook is like a sorceress who dispenses happiness.", author: "Elsa Schiaparelli" },
  { text: "The table is a meeting place, a gathering ground, the source of sustenance and nourishment, festivity, safety, and satisfaction.", author: "Laurie Colwin" },
  { text: "If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.", author: "J.R.R. Tolkien" },
  { text: "Laughter is brightest in the place where the food is.", author: "Irish Proverb" },
  { text: "A man seldom thinks with more earnestness of anything than he does of his dinner.", author: "Samuel Johnson" },
  { text: "There is no spectacle on earth more appealing than that of a beautiful woman in the act of cooking dinner for someone she loves.", author: "Tom Wolfe" },
  { text: "Sharing food with another human being is an intimate act that should not be indulged in lightly.", author: "M.F.K. Fisher" },
  { text: "The preparation of good food is merely another expression of art, one of the joys of civilized living.", author: "Dione Lucas" },
  { text: "Food is art and science and culture and human connection, and I think being mindful of that makes the experience richer.", author: "Samin Nosrat" },
  { text: "Salt, fat, acid, and heat are the fundamental elements of good cooking.", author: "Samin Nosrat" },
  { text: "A well-made sauce will make even an elephant or a grandfather palatable.", author: "Alexandre Grimod de La Reynière" },
  { text: "Tis an ill cook that cannot lick his own fingers.", author: "William Shakespeare" },
  { text: "No one who cooks, cooks alone. Even at her most solitary, a cook in the kitchen is surrounded by generations of cooks past.", author: "Laurie Colwin" },
  { text: "Food, in the end, in our own tradition, is something holy. It's not about nutrients and calories. It's about sharing. It's about honesty. It's about identity.", author: "Louise Fresco" },
  { text: "One of the delights of life is eating with friends; second to that is talking about eating. And, for an unsurpassed double whammy, there is talking about eating while you are eating with friends.", author: "Laurie Colwin" },
  { text: "Vegetables are a must on a diet. I suggest carrot cake, zucchini bread, and pumpkin pie.", author: "Jim Davis" },
  { text: "All you need is love. But a little chocolate now and then doesn't hurt.", author: "Charles M. Schulz" },
  { text: "I am not a glutton – I am an explorer of food.", author: "Erma Bombeck" },
  { text: "There is no sincerer love than the love of food.", author: "George Bernard Shaw" },
  { text: "Ask not what you can do for your country. Ask what's for lunch.", author: "Orson Welles" },
  { text: "Seize the moment. Remember all those women on the Titanic who waved off the dessert cart.", author: "Erma Bombeck" },
  { text: "I cook with wine, sometimes I even add it to the food.", author: "W.C. Fields" },
  { text: "Let food be thy medicine, thy medicine shall be thy food.", author: "Hippocrates" },
  { text: "The only thing I like better than talking about food is eating.", author: "John Walters" },
  { text: "One cannot think well, love well, sleep well, if one has not dined well.", author: "Virginia Woolf" },
  { text: "After a good dinner one can forgive anybody, even one's own relations.", author: "Oscar Wilde" },
  { text: "I have made a lot of mistakes falling in love, and regretted most of them, but never the potatoes that went with them.", author: "Nora Ephron" },
  { text: "Everything you see I owe to spaghetti.", author: "Sophia Loren" },
  { text: "A balanced diet is a cookie in each hand.", author: "Barbara Johnson" },
  { text: "Nothing would be more tiresome than eating and drinking if God had not made them a pleasure as well as a necessity.", author: "Voltaire" },

  // September (244-273) — Body Respect and Gratitude
  { text: "The body is a sacred garment.", author: "Martha Graham" },
  { text: "A fit body, a calm mind, a house full of love. These things cannot be bought – they must be earned.", author: "Naval Ravikant" },
  { text: "The higher your energy level, the more efficient your body. The more efficient your body, the better you feel.", author: "Tony Robbins" },
  { text: "Movement is a medicine for creating change in a person's physical, emotional, and mental states.", author: "Carol Welch" },
  { text: "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", author: "John F. Kennedy" },
  { text: "Those who do not find time for exercise will have to find time for illness.", author: "Edward Smith-Stanley" },
  { text: "Lack of activity destroys the good condition of every human being.", author: "Plato" },
  { text: "The food you eat will either make you more healthy or less healthy. Those are your options.", author: "Dallas Clayton" },
  { text: "A man's health can be judged by which he takes two at a time – pills or stairs.", author: "Joan Welsh" },
  { text: "Health requires healthy food.", author: "Roger Williams" },
  { text: "We don't need to eat less, we need to eat right.", author: "Unknown" },
  { text: "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.", author: "Ralph Marston" },
  { text: "Sleep is the best meditation.", author: "Dalai Lama" },
  { text: "A good laugh and a long sleep are the best cures in the doctor's book.", author: "Irish Proverb" },
  { text: "Sleep is the golden chain that ties health and our bodies together.", author: "Thomas Dekker" },
  { text: "A well-spent day brings happy sleep.", author: "Leonardo da Vinci" },
  { text: "Each night, when I go to sleep, I die. And the next morning, when I wake up, I am reborn.", author: "Mahatma Gandhi" },
  { text: "Finish each day before you begin the next, and interpose a solid wall of sleep between the two.", author: "Ralph Waldo Emerson" },
  { text: "The best bridge between despair and hope is a good night's sleep.", author: "E. Joseph Cossman" },
  { text: "True silence is the rest of the mind, and is to the spirit what sleep is to the body, nourishment and refreshment.", author: "William Penn" },
  { text: "Man should forget his anger before he lies down to sleep.", author: "Mahatma Gandhi" },
  { text: "Fatigue is the best pillow.", author: "Benjamin Franklin" },
  { text: "There is a time for many words, and there is also a time for sleep.", author: "Homer" },
  { text: "Early to bed and early to rise makes a man healthy, wealthy, and wise.", author: "Benjamin Franklin" },
  { text: "Sufficient sleep, exercise, healthy food, friendship, and peace of mind are necessities, not luxuries.", author: "Mark Halperin" },
  { text: "Good health is not something we can buy. However, it can be an extremely valuable savings account.", author: "Anne Wilson Schaef" },
  { text: "Looking after my health today gives me a better hope for tomorrow.", author: "Anne Wilson Schaef" },
  { text: "If you have health, you probably will be happy, and if you have health and happiness, you have all the wealth you need.", author: "Elbert Hubbard" },
  { text: "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier.", author: "Tom Stoppard" },
  { text: "The secret of health for both mind and body is not to mourn for the past, worry about the future, but to live the present moment wisely.", author: "Buddha" },

  // October (274-304) — Digestion, Gut Health, and Well-Being
  { text: "All disease begins in the gut.", author: "Hippocrates" },
  { text: "The road to health is paved with good intestines.", author: "Sherry A. Rogers" },
  { text: "A healthy gut means a healthy mind.", author: "Unknown" },
  { text: "Good digestion is the foundation of good health.", author: "Unknown" },
  { text: "The stomach is the seat of all feeling. The gut is the seat of all intuition.", author: "Suzy Kassem" },
  { text: "Listen to your gut. It knows what's good for you.", author: "Unknown" },
  { text: "You are not what you eat, but what you digest and absorb.", author: "Unknown" },
  { text: "The microbiome is the gateway to health.", author: "Robynne Chutkan" },
  { text: "Chew your drink and drink your food.", author: "Mahatma Gandhi" },
  { text: "Drink your tea slowly and reverently.", author: "Thich Nhat Hanh" },
  { text: "The time to relax is when you don't have time for it.", author: "Sydney J. Harris" },
  { text: "Stress is caused by being here but wanting to be there.", author: "Eckhart Tolle" },
  { text: "Tension is who you think you should be. Relaxation is who you are.", author: "Chinese Proverb" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
  { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Within you there is a stillness and a sanctuary to which you can retreat at any time and be yourself.", author: "Hermann Hesse" },
  { text: "In today's rush, we all think too much, seek too much, want too much, and forget about the joy of just being.", author: "Eckhart Tolle" },
  { text: "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.", author: "Prasad Mahes" },
  { text: "Mindfulness is a way of befriending ourselves and our experience.", author: "Jon Kabat-Zinn" },
  { text: "Be where you are, not where you think you should be.", author: "Unknown" },
  { text: "Every breath we take, every step we make, can be filled with peace, joy and serenity.", author: "Thich Nhat Hanh" },
  { text: "Peace is present right here and now, in ourselves and in everything we do and see.", author: "Thich Nhat Hanh" },
  { text: "Nothing is permanent.", author: "Buddha" },
  { text: "The root of suffering is attachment.", author: "Buddha" },
  { text: "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go of things not meant for you.", author: "Buddha" },
  { text: "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.", author: "Buddha" },
  { text: "Every morning we are born again. What we do today is what matters most.", author: "Buddha" },
  { text: "There is no path to happiness: happiness is the path.", author: "Buddha" },
  { text: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", author: "Buddha" },
  { text: "All that we are is the result of what we have thought.", author: "Buddha" },

  // November (305-334) — Gratitude and Intentional Eating
  { text: "When you eat an orange, try to practice mindful eating. Do not think of anything else, just enjoy the orange.", author: "Thich Nhat Hanh" },
  { text: "In the present moment, you have everything you need.", author: "Thich Nhat Hanh" },
  { text: "If while eating, we destroy living beings or the environment, we are eating the flesh of our own sons and daughters.", author: "Thich Nhat Hanh" },
  { text: "Mindful eating is eating with intention and attention.", author: "Jan Chozen Bays" },
  { text: "The pleasure of eating should be an extensive pleasure, not that of the mere gourmet.", author: "Wendell Berry" },
  { text: "How we eat reflects how we live.", author: "Unknown" },
  { text: "The table is a place of grace, of community, of nourishment for body and soul.", author: "Unknown" },
  { text: "Give thanks for a little and you will find a lot.", author: "Hausa Proverb" },
  { text: "Gratitude is the healthiest of all human emotions.", author: "Zig Ziglar" },
  { text: "Cultivate the habit of being grateful for every good thing that comes to you, and to give thanks continuously.", author: "Ralph Waldo Emerson" },
  { text: "Gratitude turns what we have into enough.", author: "Anonymous" },
  { text: "Be thankful for what you have; you'll end up having more. If you concentrate on what you don't have, you will never, ever have enough.", author: "Oprah Winfrey" },
  { text: "The more you praise and celebrate your life, the more there is in life to celebrate.", author: "Oprah Winfrey" },
  { text: "When eating fruit, remember the one who planted the tree.", author: "Vietnamese Proverb" },
  { text: "He who eats another's bread is obliged to sing another's song.", author: "German Proverb" },
  { text: "Better a small serving of vegetables with love than a fattened calf with hatred.", author: "King Solomon" },
  { text: "Better a dry crust with peace than a house full of feasting with strife.", author: "King Solomon" },
  { text: "A feast is made for laughter, and wine makes life merry.", author: "King Solomon" },
  { text: "Go, eat your food with gladness, and drink your wine with a joyful heart.", author: "King Solomon" },
  { text: "There is nothing better for a person than to eat and drink and find satisfaction in their own toil.", author: "King Solomon" },
  { text: "The blessing of the Lord brings wealth, without painful toil for it.", author: "King Solomon" },
  { text: "Blessed are those who hunger and thirst for righteousness, for they will be filled.", author: "Jesus Christ" },
  { text: "Man shall not live on bread alone.", author: "Jesus Christ" },
  { text: "I have food to eat that you know nothing about.", author: "Jesus Christ" },
  { text: "I am the bread of life. Whoever comes to me will never go hungry.", author: "Jesus Christ" },
  { text: "Do not worry about your life, what you will eat or drink.", author: "Jesus Christ" },
  { text: "Give us today our daily bread.", author: "Jesus Christ" },
  { text: "Earth provides enough to satisfy every man's needs, but not every man's greed.", author: "Mahatma Gandhi" },
  { text: "The world has enough for everyone's need, but not enough for everyone's greed.", author: "Mahatma Gandhi" },
  { text: "Live simply so that others may simply live.", author: "Mahatma Gandhi" },

  // December (335-366) — Reflection, Renewal, and New Beginnings
  { text: "This is my food. This is my body. This is my life. I choose carefully.", author: "Unknown" },
  { text: "Every meal is a chance to nourish yourself with love.", author: "Unknown" },
  { text: "Let food be fuel for your best life.", author: "Unknown" },
  { text: "Today I eat for energy. Today I eat for life.", author: "Unknown" },
  { text: "What nourishes me, destroys me.", author: "Angelina Jolie" },
  { text: "The only thing I'll ever ask of you: eat mindfully.", author: "Unknown" },
  { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus" },
  { text: "For last year's words belong to last year's language. And next year's words await another voice.", author: "T.S. Eliot" },
  { text: "Tomorrow is the first blank page of a 365-page book. Write a good one.", author: "Brad Paisley" },
  { text: "And now we welcome the new year, full of things that have never been.", author: "Rainer Maria Rilke" },
  { text: "Year's end is neither an end nor a beginning but a going on.", author: "Hal Borland" },
  { text: "The beginning is always today.", author: "Mary Shelley" },
  { text: "Every day is a new beginning. Take a deep breath, smile, and start again.", author: "Unknown" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "An ounce of practice is worth more than tons of preaching.", author: "Mahatma Gandhi" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "Action expresses priorities.", author: "Mahatma Gandhi" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
  { text: "There is more to life than increasing its speed.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "You may never know what results come of your actions, but if you do nothing, there will be no results.", author: "Mahatma Gandhi" },
  { text: "The difference between what we do and what we are capable of doing would suffice to solve most of the world's problems.", author: "Mahatma Gandhi" },
  { text: "Glory lies in the attempt to reach one's goal and not in reaching it.", author: "Mahatma Gandhi" },
  { text: "Each day provides its own gifts.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive—to breathe, to think, to enjoy, to love.", author: "Marcus Aurelius" },
];

// Helper to get today's quote based on day of year
export function getTodayQuote(): DailyQuote {
  const now = new Date();
  const startOfYear = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - startOfYear.getTime()) / 86400000);
  return DAILY_QUOTES[dayOfYear % DAILY_QUOTES.length];
}
