// ── 365 Daily Quotes for Mindful Eating ──────────────────────────────────────
// Attributed quotes from notable figures on food, health, discipline, and mindfulness
export interface DailyQuote {
  text: string;
  author: string;
}

export const DAILY_QUOTES: DailyQuote[] = [
  // January (1-31)
  { text: "Let food be thy medicine and medicine be thy food.", author: "Hippocrates" },
  { text: "One cannot think well, love well, sleep well, if one has not dined well.", author: "Virginia Woolf" },
  { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
  { text: "He who has health has hope, and he who has hope has everything.", author: "Arabian Proverb" },
  { text: "To keep the body in good health is a duty... otherwise we shall not be able to keep our mind strong and clear.", author: "Buddha" },
  { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
  { text: "When diet is wrong, medicine is of no use. When diet is correct, medicine is of no need.", author: "Ayurvedic Proverb" },
  { text: "Eat breakfast like a king, lunch like a prince, and dinner like a pauper.", author: "Adelle Davis" },
  { text: "Your diet is a bank account. Good food choices are good investments.", author: "Bethenny Frankel" },
  { text: "The food you eat can be either the safest and most powerful form of medicine or the slowest form of poison.", author: "Ann Wigmore" },
  { text: "Those who think they have no time for healthy eating will sooner or later have to find time for illness.", author: "Edward Stanley" },
  { text: "Every time you eat or drink, you are either feeding disease or fighting it.", author: "Heather Morgan" },
  { text: "Don't eat anything your great-grandmother wouldn't recognize as food.", author: "Michael Pollan" },
  { text: "Eat food. Not too much. Mostly plants.", author: "Michael Pollan" },
  { text: "We are indeed much more than what we eat, but what we eat can nevertheless help us to be much more than what we are.", author: "Adelle Davis" },
  { text: "It is health that is real wealth and not pieces of gold and silver.", author: "Mahatma Gandhi" },
  { text: "The groundwork for all happiness is good health.", author: "Leigh Hunt" },
  { text: "A healthy outside starts from the inside.", author: "Robert Urich" },
  { text: "Health is not valued till sickness comes.", author: "Thomas Fuller" },
  { text: "Healing is a matter of time, but it is sometimes also a matter of opportunity.", author: "Hippocrates" },
  { text: "The greatest wealth is health.", author: "Virgil" },
  { text: "Our bodies are our gardens – our wills are our gardeners.", author: "William Shakespeare" },
  { text: "Early to bed and early to rise makes a man healthy, wealthy, and wise.", author: "Benjamin Franklin" },
  { text: "Happiness is the highest form of health.", author: "Dalai Lama" },
  { text: "If you don't take care of your body, where are you going to live?", author: "Unknown" },
  { text: "Healthy citizens are the greatest asset any country can have.", author: "Winston Churchill" },
  { text: "To eat is a necessity, but to eat intelligently is an art.", author: "François de La Rochefoucauld" },
  { text: "The wise man should consider that health is the greatest of human blessings.", author: "Hippocrates" },
  { text: "A fit body, a calm mind, a house full of love. These things cannot be bought – they must be earned.", author: "Naval Ravikant" },
  { text: "Health is a state of complete harmony of the body, mind, and spirit.", author: "B.K.S. Iyengar" },
  { text: "The body achieves what the mind believes.", author: "Napoleon Hill" },

  // February (32-59)
  { text: "Compulsive eating is only the symptom; believing that you are not worth your own love is the problem.", author: "Geneen Roth" },
  { text: "We don't need to eat less, we need to eat right.", author: "Unknown" },
  { text: "No disease that can be treated by diet should be treated with any other means.", author: "Maimonides" },
  { text: "You can't out-exercise a bad diet.", author: "Mark Hyman" },
  { text: "Processed foods not only extend the shelf life, but they extend the waistline as well.", author: "Karen Sessions" },
  { text: "If it came from a plant, eat it. If it was made in a plant, don't.", author: "Michael Pollan" },
  { text: "The doctor of the future will no longer treat the human frame with drugs, but rather will cure and prevent disease with nutrition.", author: "Thomas Edison" },
  { text: "What you eat literally becomes you. You have a choice in what you're made of.", author: "Unknown" },
  { text: "Eating crappy food isn't a reward – it's a punishment.", author: "Drew Carey" },
  { text: "Life expectancy would grow by leaps and bounds if green vegetables smelled as good as bacon.", author: "Doug Larson" },
  { text: "When walking, walk. When eating, eat.", author: "Zen Proverb" },
  { text: "The belly rules the mind.", author: "Spanish Proverb" },
  { text: "Tell me what you eat, and I will tell you who you are.", author: "Jean Anthelme Brillat-Savarin" },
  { text: "Mindful eating is a way to become reacquainted with the guidance of our internal nutritionist.", author: "Jan Chozen Bays" },
  { text: "We never repent of having eaten too little.", author: "Thomas Jefferson" },
  { text: "Hara hachi bu — eat until you are 80% full.", author: "Okinawan Proverb" },
  { text: "The more you eat, the less flavor; the less you eat, the more flavor.", author: "Chinese Proverb" },
  { text: "Gluttony is an emotional escape, a sign something is eating us.", author: "Peter De Vries" },
  { text: "Hunger is the best sauce in the world.", author: "Miguel de Cervantes" },
  { text: "One should eat to live, not live to eat.", author: "Molière" },
  { text: "Part of the secret of success in life is to eat what you like and let the food fight it out inside.", author: "Mark Twain" },
  { text: "Leave your drugs in the chemist's pot if you can heal the patient with food.", author: "Hippocrates" },
  { text: "The only time to eat diet food is while you're waiting for the steak to cook.", author: "Julia Child" },
  { text: "After dinner rest a while; after supper walk a mile.", author: "T. Cogan" },
  { text: "Eat little, sleep sound.", author: "Iranian Proverb" },
  { text: "Better to pay the butcher than the doctor.", author: "Yiddish Proverb" },
  { text: "Our food should be our medicine and our medicine should be our food.", author: "Hippocrates" },
  { text: "Thou shouldst eat to live; not live to eat.", author: "Socrates" },

  // March (60-90)
  { text: "The discipline of desire is the background of character.", author: "John Locke" },
  { text: "He who controls others may be powerful, but he who has mastered himself is mightier still.", author: "Lao Tzu" },
  { text: "Self-discipline is the ability to make yourself do what you should do, when you should do it, whether you feel like it or not.", author: "Elbert Hubbard" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
  { text: "With self-discipline most anything is possible.", author: "Theodore Roosevelt" },
  { text: "In reading the lives of great men, I found that the first victory they won was over themselves... self-discipline with all of them came first.", author: "Harry S. Truman" },
  { text: "Self-command is the main elegance.", author: "Ralph Waldo Emerson" },
  { text: "No man is free who is not master of himself.", author: "Epictetus" },
  { text: "Rule your mind or it will rule you.", author: "Horace" },
  { text: "The first and greatest victory is to conquer yourself.", author: "Plato" },
  { text: "Most powerful is he who has himself in his own power.", author: "Seneca" },
  { text: "He who cannot obey himself will be commanded.", author: "Friedrich Nietzsche" },
  { text: "Self-discipline begins with the mastery of your thoughts.", author: "Napoleon Hill" },
  { text: "Without discipline, there's no life at all.", author: "Katharine Hepburn" },
  { text: "What we do today is what matters most.", author: "Buddha" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
  { text: "I don't count my sit-ups; I only start counting when it starts hurting because they're the only ones that count.", author: "Muhammad Ali" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
  { text: "Do not pray for an easy life, pray for the strength to endure a difficult one.", author: "Bruce Lee" },
  { text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi" },
  { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
  { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
  { text: "Your body hears everything your mind says.", author: "Naomi Judd" },
  { text: "The mind is everything. What you think you become.", author: "Buddha" },
  { text: "Be patient with yourself. Self-growth is tender; it's holy ground.", author: "Stephen Covey" },
  { text: "You must expect great things of yourself before you can do them.", author: "Michael Jordan" },
  { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
  { text: "The hardest battle you'll ever fight is the battle to be yourself.", author: "E.E. Cummings" },

  // April (91-120)
  { text: "All that we are is the result of what we have thought.", author: "Buddha" },
  { text: "The soul always knows what to do to heal itself. The challenge is to silence the mind.", author: "Caroline Myss" },
  { text: "Healing takes courage, and we all have courage, even if we have to dig a little to find it.", author: "Tori Amos" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi" },
  { text: "What drains your spirit drains your body. What fuels your spirit fuels your body.", author: "Caroline Myss" },
  { text: "Almost everything will work again if you unplug it for a few minutes, including you.", author: "Anne Lamott" },
  { text: "Self-care is not self-indulgence, it is self-preservation.", author: "Audre Lorde" },
  { text: "Caring for your body, mind, and spirit is your greatest and grandest responsibility.", author: "Deepak Chopra" },
  { text: "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit.", author: "Ralph Marston" },
  { text: "To keep the body in good health is a duty.", author: "Buddha" },
  { text: "The greatest healing therapy is friendship and love.", author: "Hubert H. Humphrey" },
  { text: "Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.", author: "Thich Nhat Hanh" },
  { text: "When you eat, just eat. When you walk, just walk.", author: "Thich Nhat Hanh" },
  { text: "Drink your tea slowly and reverently, as if it is the axis on which the world revolves.", author: "Thich Nhat Hanh" },
  { text: "Every breath we take, every step we make, can be filled with peace, joy and serenity.", author: "Thich Nhat Hanh" },
  { text: "Peace is present right here and now, in ourselves and in everything we do and see.", author: "Thich Nhat Hanh" },
  { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh" },
  { text: "Mindfulness is a way of befriending ourselves and our experience.", author: "Jon Kabat-Zinn" },
  { text: "Be where you are, not where you think you should be.", author: "Unknown" },
  { text: "In today's rush, we all think too much, seek too much, want too much, and forget about the joy of just being.", author: "Eckhart Tolle" },
  { text: "The mind is like water. When it's turbulent, it's difficult to see. When it's calm, everything becomes clear.", author: "Prasad Mahes" },
  { text: "Within you there is a stillness and a sanctuary to which you can retreat at any time and be yourself.", author: "Hermann Hesse" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu" },
  { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
  { text: "Less is more.", author: "Ludwig Mies van der Rohe" },
  { text: "It is not the daily increase but daily decrease. Hack away at the unessential.", author: "Bruce Lee" },
  { text: "The ability to simplify means to eliminate the unnecessary so that the necessary may speak.", author: "Hans Hofmann" },
  { text: "Our life is frittered away by detail. Simplify, simplify.", author: "Henry David Thoreau" },
  { text: "Have nothing in your houses that you do not know to be useful or believe to be beautiful.", author: "William Morris" },
  { text: "The secret of happiness is not in doing what one likes, but in liking what one does.", author: "James M. Barrie" },

  // May (121-151)
  { text: "You are what you eat, so don't be fast, cheap, easy, or fake.", author: "Unknown" },
  { text: "Health requires healthy food.", author: "Roger Williams" },
  { text: "The human body is the best picture of the human soul.", author: "Ludwig Wittgenstein" },
  { text: "Those who do not find time for exercise will have to find time for illness.", author: "Edward Smith-Stanley" },
  { text: "Physical fitness is not only one of the most important keys to a healthy body, it is the basis of dynamic and creative intellectual activity.", author: "John F. Kennedy" },
  { text: "Take care of your body with steadfast fidelity.", author: "Johann Wolfgang von Goethe" },
  { text: "The higher your energy level, the more efficient your body. The more efficient your body, the better you feel.", author: "Tony Robbins" },
  { text: "Movement is a medicine for creating change in a person's physical, emotional, and mental states.", author: "Carol Welch" },
  { text: "The body is your temple. Keep it pure and clean for the soul to reside in.", author: "B.K.S. Iyengar" },
  { text: "A man's health can be judged by which he takes two at a time – pills or stairs.", author: "Joan Welsh" },
  { text: "Lack of activity destroys the good condition of every human being.", author: "Plato" },
  { text: "A man too busy to take care of his health is like a mechanic too busy to take care of his tools.", author: "Spanish Proverb" },
  { text: "True silence is the rest of the mind, and is to the spirit what sleep is to the body, nourishment and refreshment.", author: "William Penn" },
  { text: "Sleep is the best meditation.", author: "Dalai Lama" },
  { text: "The best bridge between despair and hope is a good night's sleep.", author: "E. Joseph Cossman" },
  { text: "Finish each day before you begin the next, and interpose a solid wall of sleep between the two.", author: "Ralph Waldo Emerson" },
  { text: "A good laugh and a long sleep are the best cures in the doctor's book.", author: "Irish Proverb" },
  { text: "Each night, when I go to sleep, I die. And the next morning, when I wake up, I am reborn.", author: "Mahatma Gandhi" },
  { text: "There is a time for many words, and there is also a time for sleep.", author: "Homer" },
  { text: "Sleep is the golden chain that ties health and our bodies together.", author: "Thomas Dekker" },
  { text: "Man should forget his anger before he lies down to sleep.", author: "Mahatma Gandhi" },
  { text: "Fatigue is the best pillow.", author: "Benjamin Franklin" },
  { text: "A well-spent day brings happy sleep.", author: "Leonardo da Vinci" },
  { text: "I have never taken any exercise except sleeping and resting.", author: "Mark Twain" },
  { text: "Even a soul submerged in sleep is hard at work.", author: "Heraclitus" },
  { text: "Rest is not idleness.", author: "John Lubbock" },
  { text: "Sometimes the most productive thing you can do is rest.", author: "Mark Black" },
  { text: "It is better to rise from life as from a banquet – neither thirsty nor drunken.", author: "Aristotle" },
  { text: "Moderation in all things, especially moderation.", author: "Ralph Waldo Emerson" },
  { text: "The key is balance.", author: "Unknown" },
  { text: "Balance is not something you find, it's something you create.", author: "Jana Kingsford" },

  // June (152-181)
  { text: "Fasting is the first principle of medicine; fast and see the strength of the spirit reveal itself.", author: "Rumi" },
  { text: "Everyone has a doctor in him or her; we just have to help it in its work.", author: "Hippocrates" },
  { text: "The best of all medicines is resting and fasting.", author: "Benjamin Franklin" },
  { text: "Instead of using medicine, rather, fast a day.", author: "Plutarch" },
  { text: "To lengthen thy life, lessen thy meals.", author: "Benjamin Franklin" },
  { text: "I fast for greater physical and mental efficiency.", author: "Plato" },
  { text: "Fasting is the greatest remedy – the physician within.", author: "Paracelsus" },
  { text: "A little starvation can really do more for the average sick man than can the best medicines.", author: "Mark Twain" },
  { text: "Nature heals, the doctor only helps.", author: "Paracelsus" },
  { text: "The natural healing force within each of us is the greatest force in getting well.", author: "Hippocrates" },
  { text: "Healing is not forcing the sun to shine, but letting go of that which blocks the light.", author: "Stephen Levine" },
  { text: "The art of healing comes from nature, not from the physician.", author: "Paracelsus" },
  { text: "Before healing others, heal yourself.", author: "Gambian Proverb" },
  { text: "Keeping your body healthy is an expression of gratitude to the whole cosmos.", author: "Thich Nhat Hanh" },
  { text: "A healthy attitude is contagious but don't wait to catch it from others. Be a carrier.", author: "Tom Stoppard" },
  { text: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha" },
  { text: "Sufficient sleep, exercise, healthy food, friendship, and peace of mind are necessities, not luxuries.", author: "Mark Halperin" },
  { text: "Good health is not something we can buy. However, it can be an extremely valuable savings account.", author: "Anne Wilson Schaef" },
  { text: "Prevention is better than cure.", author: "Desiderius Erasmus" },
  { text: "An ounce of prevention is worth a pound of cure.", author: "Benjamin Franklin" },
  { text: "Looking after my health today gives me a better hope for tomorrow.", author: "Anne Wilson Schaef" },
  { text: "If you have health, you probably will be happy, and if you have health and happiness, you have all the wealth you need.", author: "Elbert Hubbard" },
  { text: "The secret of health for both mind and body is not to mourn for the past, worry about the future, but to live the present moment wisely.", author: "Buddha" },
  { text: "Time and health are two precious assets that we don't recognize and appreciate until they have been depleted.", author: "Denis Waitley" },
  { text: "He who has health, has hope; and he who has hope, has everything.", author: "Thomas Carlyle" },
  { text: "The wish for healing has always been half of health.", author: "Seneca" },
  { text: "It is no measure of health to be well adjusted to a profoundly sick society.", author: "Jiddu Krishnamurti" },
  { text: "I believe that the greatest gift you can give your family and the world is a healthy you.", author: "Joyce Meyer" },
  { text: "Nurturing yourself is not selfish – it's essential to your survival and your well-being.", author: "Renee Peterson Trudeau" },
  { text: "Love yourself first and everything else falls into line.", author: "Lucille Ball" },

  // July (182-212)
  { text: "The body is a sacred garment.", author: "Martha Graham" },
  { text: "Your body is precious. It is our vehicle for awakening. Treat it with care.", author: "Buddha" },
  { text: "I finally realized that being grateful to my body was key to giving more love to myself.", author: "Oprah Winfrey" },
  { text: "To love oneself is the beginning of a lifelong romance.", author: "Oscar Wilde" },
  { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius" },
  { text: "Choose not to be harmed – and you won't feel harmed. Don't feel harmed – and you haven't been.", author: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
  { text: "Accept the things to which fate binds you, and love the people with whom fate brings you together.", author: "Marcus Aurelius" },
  { text: "You have power over your mind – not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
  { text: "Never let the future disturb you. You will meet it with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius" },
  { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
  { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
  { text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius" },
  { text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius" },
  { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius" },
  { text: "How much time he gains who does not look to see what his neighbor says or does or thinks.", author: "Marcus Aurelius" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca" },
  { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
  { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
  { text: "True happiness is to enjoy the present, without anxious dependence upon the future.", author: "Seneca" },
  { text: "It is the power of the mind to be unconquerable.", author: "Seneca" },

  // August (213-243)
  { text: "Associate with people who are likely to improve you.", author: "Seneca" },
  { text: "While we are postponing, life speeds by.", author: "Seneca" },
  { text: "He suffers more than necessary, who suffers before it is necessary.", author: "Seneca" },
  { text: "No person has the power to have everything they want, but it is in their power not to want what they don't have.", author: "Seneca" },
  { text: "If a man knows not to which port he sails, no wind is favorable.", author: "Seneca" },
  { text: "The mind that is anxious about future events is miserable.", author: "Seneca" },
  { text: "Wealth is the slave of a wise man and the master of a fool.", author: "Seneca" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus" },
  { text: "It's not what happens to you, but how you react to it that matters.", author: "Epictetus" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
  { text: "Man is not worried by real problems so much as by his imagined anxieties about real problems.", author: "Epictetus" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus" },
  { text: "We have two ears and one mouth so that we can listen twice as much as we speak.", author: "Epictetus" },
  { text: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus" },
  { text: "Only the educated are free.", author: "Epictetus" },
  { text: "The key is to keep company only with people who uplift you.", author: "Epictetus" },
  { text: "Circumstances don't make the man, they only reveal him to himself.", author: "Epictetus" },
  { text: "Caretake this moment. Immerse yourself in its particulars.", author: "Epictetus" },
  { text: "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.", author: "Epictetus" },
  { text: "Practice yourself, for heaven's sake, in little things; and thence proceed to greater.", author: "Epictetus" },
  { text: "Don't just say you have read books. Show that through them you have learned to think better.", author: "Epictetus" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Know thyself.", author: "Socrates" },
  { text: "To find yourself, think for yourself.", author: "Socrates" },
  { text: "I cannot teach anybody anything. I can only make them think.", author: "Socrates" },
  { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
  { text: "Be kind, for everyone you meet is fighting a hard battle.", author: "Plato" },
  { text: "Good actions give strength to ourselves and inspire good actions in others.", author: "Plato" },
  { text: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author: "Plato" },

  // September (244-273)
  { text: "The measure of a man is what he does with power.", author: "Plato" },
  { text: "Music gives a soul to the universe, wings to the mind, flight to the imagination and life to everything.", author: "Plato" },
  { text: "Courage is knowing what not to fear.", author: "Plato" },
  { text: "The beginning is the most important part of the work.", author: "Plato" },
  { text: "Human behavior flows from three main sources: desire, emotion, and knowledge.", author: "Plato" },
  { text: "At the touch of love everyone becomes a poet.", author: "Plato" },
  { text: "Wise men speak because they have something to say; Fools because they have to say something.", author: "Plato" },
  { text: "Excellence is not a gift, but a skill that takes practice.", author: "Plato" },
  { text: "Thinking: the talking of the soul with itself.", author: "Plato" },
  { text: "Education is teaching our children to desire the right things.", author: "Plato" },
  { text: "The soul takes nothing with her to the next world but her education and culture.", author: "Plato" },
  { text: "No law or ordinance is mightier than understanding.", author: "Plato" },
  { text: "I am the wisest man alive, for I know one thing, and that is that I know nothing.", author: "Plato" },
  { text: "In every walk with nature one receives far more than he seeks.", author: "John Muir" },
  { text: "Keep close to Nature's heart and break clear away, once in a while.", author: "John Muir" },
  { text: "The clearest way into the Universe is through a forest wilderness.", author: "John Muir" },
  { text: "Between every two pines is a doorway to a new world.", author: "John Muir" },
  { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
  { text: "Study nature, love nature, stay close to nature. It will never fail you.", author: "Frank Lloyd Wright" },
  { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson" },
  { text: "Just living is not enough. One must have sunshine, freedom, and a little flower.", author: "Hans Christian Andersen" },
  { text: "Let food be thy medicine.", author: "Hippocrates" },
  { text: "Walking is man's best medicine.", author: "Hippocrates" },
  { text: "Natural forces within us are the true healers of disease.", author: "Hippocrates" },
  { text: "If we could give every individual the right amount of nourishment and exercise, we would have found the safest way to health.", author: "Hippocrates" },
  { text: "A wise man ought to realize that health is his most valuable possession.", author: "Hippocrates" },
  { text: "All disease begins in the gut.", author: "Hippocrates" },
  { text: "Make a habit of two things: to help; or at least to do no harm.", author: "Hippocrates" },
  { text: "Cure sometimes, treat often, comfort always.", author: "Hippocrates" },
  { text: "The function of protecting and developing health must rank even above that of restoring it when it is impaired.", author: "Hippocrates" },

  // October (274-304)
  { text: "What you think, you become. What you feel, you attract. What you imagine, you create.", author: "Buddha" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
  { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
  { text: "Three things cannot be long hidden: the sun, the moon, and the truth.", author: "Buddha" },
  { text: "You yourself, as much as anybody in the entire universe, deserve your love and affection.", author: "Buddha" },
  { text: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", author: "Buddha" },
  { text: "Thousands of candles can be lighted from a single candle. Happiness never decreases by being shared.", author: "Buddha" },
  { text: "Every morning we are born again. What we do today is what matters most.", author: "Buddha" },
  { text: "There is no path to happiness: happiness is the path.", author: "Buddha" },
  { text: "Nothing is permanent.", author: "Buddha" },
  { text: "Just as a candle cannot burn without fire, men cannot live without a spiritual life.", author: "Buddha" },
  { text: "The root of suffering is attachment.", author: "Buddha" },
  { text: "In the end, only three things matter: how much you loved, how gently you lived, and how gracefully you let go.", author: "Buddha" },
  { text: "If you light a lamp for somebody, it will also brighten your path.", author: "Buddha" },
  { text: "Your work is to discover your world and then with all your heart give yourself to it.", author: "Buddha" },
  { text: "There are only two mistakes one can make along the road to truth; not going all the way, and not starting.", author: "Buddha" },
  { text: "An idea that is developed and put into action is more important than an idea that exists only as an idea.", author: "Buddha" },
  { text: "Better than a thousand hollow words, is one word that brings peace.", author: "Buddha" },
  { text: "Health is the greatest possession. Contentment is the greatest treasure. Confidence is the greatest friend.", author: "Lao Tzu" },
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
  { text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu" },
  { text: "The wise man is one who knows what he does not know.", author: "Lao Tzu" },
  { text: "Those who know do not speak. Those who speak do not know.", author: "Lao Tzu" },
  { text: "Great acts are made up of small deeds.", author: "Lao Tzu" },
  { text: "Silence is a source of great strength.", author: "Lao Tzu" },
  { text: "If you are depressed you are living in the past. If you are anxious you are living in the future. If you are at peace you are living in the present.", author: "Lao Tzu" },
  { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
  { text: "Tension is who you think you should be. Relaxation is who you are.", author: "Chinese Proverb" },
  { text: "Give a man a fish and you feed him for a day. Teach him how to fish and you feed him for a lifetime.", author: "Lao Tzu" },
  { text: "Care about what other people think and you will always be their prisoner.", author: "Lao Tzu" },

  // November (305-334)
  { text: "Knowing others is intelligence; knowing yourself is true wisdom.", author: "Lao Tzu" },
  { text: "Mastering others is strength; mastering yourself is true power.", author: "Lao Tzu" },
  { text: "The snow goose need not bathe to make itself white. Neither need you do anything but be yourself.", author: "Lao Tzu" },
  { text: "Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow.", author: "Lao Tzu" },
  { text: "New beginnings are often disguised as painful endings.", author: "Lao Tzu" },
  { text: "To a mind that is still, the whole universe surrenders.", author: "Lao Tzu" },
  { text: "Watch your thoughts, they become your words; watch your words, they become your actions.", author: "Lao Tzu" },
  { text: "If you realize that all things change, there is nothing you will try to hold on to.", author: "Lao Tzu" },
  { text: "Act without expectation.", author: "Lao Tzu" },
  { text: "When you are content to be simply yourself and don't compare or compete, everybody will respect you.", author: "Lao Tzu" },
  { text: "The flame that burns twice as bright burns half as long.", author: "Lao Tzu" },
  { text: "Do the difficult things while they are easy and do the great things while they are small.", author: "Lao Tzu" },
  { text: "Stop thinking, and end your problems.", author: "Lao Tzu" },
  { text: "Respond intelligently even to unintelligent treatment.", author: "Lao Tzu" },
  { text: "Simplicity, patience, compassion. These three are your greatest treasures.", author: "Lao Tzu" },
  { text: "He who knows that enough is enough will always have enough.", author: "Lao Tzu" },
  { text: "In dwelling, live close to the ground. In thinking, keep to the simple.", author: "Lao Tzu" },
  { text: "The journey of a thousand miles begins beneath your feet.", author: "Lao Tzu" },
  { text: "To attain knowledge, add things every day. To attain wisdom, remove things every day.", author: "Lao Tzu" },
  { text: "I have just three things to teach: simplicity, patience, compassion.", author: "Lao Tzu" },
  { text: "He who conquers others is strong; he who conquers himself is mighty.", author: "Lao Tzu" },
  { text: "Be content with what you have; rejoice in the way things are.", author: "Lao Tzu" },
  { text: "Water is the softest thing, yet it can penetrate mountains and earth.", author: "Lao Tzu" },
  { text: "Because one believes in oneself, one doesn't try to convince others.", author: "Lao Tzu" },
  { text: "Fill your bowl to the brim and it will spill. Keep sharpening your knife and it will blunt.", author: "Lao Tzu" },
  { text: "The truth is not always beautiful, nor beautiful words the truth.", author: "Lao Tzu" },
  { text: "By letting go it all gets done.", author: "Lao Tzu" },
  { text: "The best fighter is never angry.", author: "Lao Tzu" },
  { text: "When you realize nothing is lacking, the whole world belongs to you.", author: "Lao Tzu" },
  { text: "Treat those who are good with goodness, and also treat those who are not good with goodness.", author: "Lao Tzu" },

  // December (335-366)
  { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "The price of greatness is responsibility.", author: "Winston Churchill" },
  { text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill" },
  { text: "You will never reach your destination if you stop and throw stones at every dog that barks.", author: "Winston Churchill" },
  { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
  { text: "Kites rise highest against the wind – not with it.", author: "Winston Churchill" },
  { text: "If you're going through hell, keep going.", author: "Winston Churchill" },
  { text: "Never, never, never give up.", author: "Winston Churchill" },
  { text: "Every day is a new beginning. Take a deep breath, smile, and start again.", author: "Unknown" },
  { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
  { text: "Keep your face always toward the sunshine – and shadows will fall behind you.", author: "Walt Whitman" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
  { text: "An ounce of practice is worth more than tons of preaching.", author: "Mahatma Gandhi" },
  { text: "The weak can never forgive. Forgiveness is the attribute of the strong.", author: "Mahatma Gandhi" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
  { text: "The best way to find yourself is to lose yourself in the service of others.", author: "Mahatma Gandhi" },
  { text: "Action expresses priorities.", author: "Mahatma Gandhi" },
  { text: "First they ignore you, then they laugh at you, then they fight you, then you win.", author: "Mahatma Gandhi" },
  { text: "Earth provides enough to satisfy every man's needs, but not every man's greed.", author: "Mahatma Gandhi" },
  { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
  { text: "There is more to life than increasing its speed.", author: "Mahatma Gandhi" },
  { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
  { text: "Glory lies in the attempt to reach one's goal and not in reaching it.", author: "Mahatma Gandhi" },
  { text: "You may never know what results come of your actions, but if you do nothing, there will be no results.", author: "Mahatma Gandhi" },
  { text: "The difference between what we do and what we are capable of doing would suffice to solve most of the world's problems.", author: "Mahatma Gandhi" },
  { text: "Each day provides its own gifts.", author: "Marcus Aurelius" },
];

// Helper to get today's quote based on day of year
export function getTodayQuote(): DailyQuote {
  const now = new Date();
  const startOfYear = new Date(now.getFullYear(), 0, 0);
  const dayOfYear = Math.floor((now.getTime() - startOfYear.getTime()) / 86400000);
  return DAILY_QUOTES[dayOfYear % DAILY_QUOTES.length];
}
